In [3]:
import numpy as np
import pandas as pd
import matplotlib as plt
%matplotlib inline

In [4]:
master = pd.read_csv('data/classast - pha.csv')

There are six unique classes of stars;

In [6]:
master

,a (AU),e,i (deg),w (deg),Node (deg),M (deg),q (AU),Q (AU),P (yr),H (mag),MOID (AU),class
0,1.078066,0.826854,22.825495,31.382966,88.010681,215.528772,0.1867,1.97,1.12,16.90,0.034507,APO*
1,1.245304,0.335342,13.337482,276.893024,337.207958,104.155606,0.8277,1.66,1.39,15.60,0.030669,APO*
2,1.470264,0.559922,6.352995,285.852564,35.736768,174.626213,0.6470,2.29,1.78,16.25,0.025795,APO*
3,1.776025,0.650141,39.832538,267.791993,356.903343,173.188556,0.6214,2.93,2.37,15.20,0.003551,APO*
4,1.874123,0.764602,1.326400,43.388048,349.694944,235.158622,0.4412,3.31,2.57,18.80,0.011645,APO*
...,...,...,...,...,...,...,...,...,...,...,...,...
1743,1.662826,0.382487,0.874625,304.980506,221.156655,312.111572,1.0268,2.30,2.14,21.08,0.036365,AMO*
1744,2.706630,0.764459,11.433742,282.994922,267.501145,344.253089,0.6375,4.78,4.45,20.19,0.016630,APO*
1745,2.037870,0.667525,8.906649,279.721935,64.690270,19.063147,0.6775,3.40,2.91,21.86,0.007084,APO*
1746,2.095193,0.654662,4.014503,145.429653,25.164523,340.766105,0.7235,3.47,3.03,21.91,0.044428,APO*
1747,2.804294,0.667236,4.724883,234.125980,183.574675,349.530160,0.9332,4.68,4.70,20.40,0.028788,APO*

In [9]:
master['class'].unique()

array(['APO*', 'ATE*', 'AMO*', 'APO', 'IEO*', 'ATE'], dtype=object)